In [1]:
import pandas as pd

In [24]:
df = pd.read_csv("/home/ismael/Downloads/spotify_churn_dataset.csv")

In [25]:
df.isnull().sum()

user_id                  0
gender                   0
age                      0
country                  0
subscription_type        0
listening_time           0
songs_played_per_day     0
skip_rate                0
device_type              0
ads_listened_per_week    0
offline_listening        0
is_churned               0
dtype: int64

In [26]:
df

,user_id,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
0,1,Female,54,CA,Free,26,23,0.20,Desktop,31,0,1
1,2,Other,33,DE,Family,141,62,0.34,Web,0,1,0
2,3,Male,38,AU,Premium,199,38,0.04,Mobile,0,1,1
3,4,Female,22,CA,Student,36,2,0.31,Mobile,0,1,0
4,5,Other,29,US,Family,250,57,0.36,Mobile,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996,Other,44,DE,Student,237,36,0.30,Mobile,0,1,1
7996,7997,Male,34,AU,Premium,61,64,0.59,Mobile,0,1,0
7997,7998,Female,17,US,Free,81,62,0.33,Desktop,5,0,0
7998,7999,Female,34,IN,Student,245,94,0.27,Desktop,0,1,0
7999,8000,Other,45,AU,Free,210,68,0.46,Desktop,6,0,0

In [27]:
df["subscription_type"].unique()

array(['Free', 'Family', 'Premium', 'Student'], dtype=object)

In [28]:
df["gender"].replace({"Male" : "Masculino", "Female" : "Feminino", "Other" : "Feminino"}, inplace=True)

/tmp/ipykernel_776497/3218972783.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["gender"].replace({"Male" : "Masculino", "Female" : "Feminino", "Other" : "Feminino"}, inplace=True)

In [29]:
df["subscription_type"].replace({"Free" : "Gratuito", "Family" : "Familia", "Student" : "Estudante"}, inplace=True)

/tmp/ipykernel_776497/767632446.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["subscription_type"].replace({"Free" : "Gratuito", "Family" : "Familia", "Student" : "Estudante"}, inplace=True)

In [32]:
df.rename({"gender" : "sexo", "age" :  "idade", "subscription_type" : "tipo_assinatura", "listening_time" : "tempo_uso", "songs_played_per_day" : "musicas_por_dia", "country" : "pais",
           "skip_rate" : "taxa_pulo", "device_type" : "dispositivo", "ads_listened_per_week" : "anuncios_semana", "offline_listening" : "escuta_offline", "is_churned" : "cancelamento"}, axis=1, inplace=True)

In [33]:
df

,user_id,sexo,idade,pais,tipo_assinatura,tempo_uso,musicas_por_dia,taxa_pulo,dispositivo,anuncios_semana,escuta_offline,cancelamento
0,1,Feminino,54,CA,Gratuito,26,23,0.20,Desktop,31,0,1
1,2,Feminino,33,DE,Familia,141,62,0.34,Web,0,1,0
2,3,Masculino,38,AU,Premium,199,38,0.04,Mobile,0,1,1
3,4,Feminino,22,CA,Estudante,36,2,0.31,Mobile,0,1,0
4,5,Feminino,29,US,Familia,250,57,0.36,Mobile,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996,Feminino,44,DE,Estudante,237,36,0.30,Mobile,0,1,1
7996,7997,Masculino,34,AU,Premium,61,64,0.59,Mobile,0,1,0
7997,7998,Feminino,17,US,Gratuito,81,62,0.33,Desktop,5,0,0
7998,7999,Feminino,34,IN,Estudante,245,94,0.27,Desktop,0,1,0
7999,8000,Feminino,45,AU,Gratuito,210,68,0.46,Desktop,6,0,0

In [34]:
df.to_csv("./Processadas/spotify_tratado.csv", index=False)

In [39]:
df = pd.read_csv("/home/ismael/Downloads/microdados_enem_2023/DADOS/MICRODADOS_ENEM_2023.csv", encoding="latin-1", sep=";")

In [42]:
df.columns

Index(['NU_INSCRICAO', 'NU_ANO', 'TP_FAIXA_ETARIA', 'TP_SEXO',
       'TP_ESTADO_CIVIL', 'TP_COR_RACA', 'TP_NACIONALIDADE', 'TP_ST_CONCLUSAO',
       'TP_ANO_CONCLUIU', 'TP_ESCOLA', 'TP_ENSINO', 'IN_TREINEIRO',
       'CO_MUNICIPIO_ESC', 'NO_MUNICIPIO_ESC', 'CO_UF_ESC', 'SG_UF_ESC',
       'TP_DEPENDENCIA_ADM_ESC', 'TP_LOCALIZACAO_ESC', 'TP_SIT_FUNC_ESC',
       'CO_MUNICIPIO_PROVA', 'NO_MUNICIPIO_PROVA', 'CO_UF_PROVA',
       'SG_UF_PROVA', 'TP_PRESENCA_CN', 'TP_PRESENCA_CH', 'TP_PRESENCA_LC',
       'TP_PRESENCA_MT', 'CO_PROVA_CN', 'CO_PROVA_CH', 'CO_PROVA_LC',
       'CO_PROVA_MT', 'NU_NOTA_CN', 'NU_NOTA_CH', 'NU_NOTA_LC', 'NU_NOTA_MT',
       'TX_RESPOSTAS_CN', 'TX_RESPOSTAS_CH', 'TX_RESPOSTAS_LC',
       'TX_RESPOSTAS_MT', 'TP_LINGUA', 'TX_GABARITO_CN', 'TX_GABARITO_CH',
       'TX_GABARITO_LC', 'TX_GABARITO_MT', 'TP_STATUS_REDACAO',
       'NU_NOTA_COMP1', 'NU_NOTA_COMP2', 'NU_NOTA_COMP3', 'NU_NOTA_COMP4',
       'NU_NOTA_COMP5', 'NU_NOTA_REDACAO', 'Q001', 'Q002', 'Q003', 'Q004',
       'Q005', 'Q006', 'Q007', 'Q008', 'Q009', 'Q010', 'Q011', 'Q012', 'Q013',
       'Q014', 'Q015', 'Q016', 'Q017', 'Q018', 'Q019', 'Q020', 'Q021', 'Q022',
       'Q023', 'Q024', 'Q025'],
      dtype='object')

In [44]:
df = df[["NU_INSCRICAO", "TP_FAIXA_ETARIA", "TP_SEXO", "TP_COR_RACA", "TP_ANO_CONCLUIU", "TP_ENSINO", "IN_TREINEIRO", "NO_MUNICIPIO_PROVA", "NU_NOTA_CN", "NU_NOTA_CH", "NU_NOTA_LC", "NU_NOTA_MT", "NU_NOTA_REDACAO", "Q005", "Q006"]]

In [45]:
df.dropna(inplace=True)

/tmp/ipykernel_776497/1379821321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [48]:
df = df.loc[df["NO_MUNICIPIO_PROVA"].isin(["Belford Roxo", "Duque de Caxias", "Maricá", "Nilópolis", "Niterói", "Nova Iguaçu", "São João de Meriti"])]

In [50]:
set(df["NO_MUNICIPIO_PROVA"])

{'Belford Roxo',
 'Duque de Caxias',
 'Maricá',
 'Nilópolis',
 'Niterói',
 'Nova Iguaçu',
 'São João de Meriti'}

In [53]:
df = df.loc[df["NU_NOTA_REDACAO"] > 0]
df = df.loc[df["NU_NOTA_CH"] > 0]
df = df.loc[df["NU_NOTA_CN"] > 0]
df = df.loc[df["NU_NOTA_MT"] > 0]
df = df.loc[df["NU_NOTA_LC"] > 0]

In [54]:
min(df["NU_NOTA_REDACAO"])

80.0

In [55]:
min(df["NU_NOTA_MT"])

328.2

In [56]:
df.dtypes

NU_INSCRICAO            int64
TP_FAIXA_ETARIA         int64
TP_SEXO                object
TP_COR_RACA             int64
TP_ANO_CONCLUIU         int64
TP_ENSINO             float64
IN_TREINEIRO            int64
NO_MUNICIPIO_PROVA     object
NU_NOTA_CN            float64
NU_NOTA_CH            float64
NU_NOTA_LC            float64
NU_NOTA_MT            float64
NU_NOTA_REDACAO       float64
Q005                    int64
Q006                   object
dtype: object

In [57]:
df.to_csv("./Processadas/dados_enem_2013.csv", index=False)

In [2]:
df = pd.read_csv("/home/ismael/Downloads/BankChurners.csv")

In [4]:
df.columns

Index(['CLIENTNUM', 'Attrition_Flag', 'Customer_Age', 'Gender',
       'Dependent_count', 'Education_Level', 'Marital_Status',
       'Income_Category', 'Card_Category', 'Months_on_book',
       'Total_Relationship_Count', 'Months_Inactive_12_mon',
       'Contacts_Count_12_mon', 'Credit_Limit', 'Total_Revolving_Bal',
       'Avg_Open_To_Buy', 'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt',
       'Total_Trans_Ct', 'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
       'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'],
      dtype='object')

In [6]:
df = df[["CLIENTNUM", "Customer_Age", "Gender", "Months_on_book", "Dependent_count", "Education_Level", "Marital_Status", "Card_Category", "Credit_Limit", "Months_Inactive_12_mon", "Total_Trans_Amt", "Attrition_Flag" ]]

In [7]:
df.isnull().sum()

CLIENTNUM                 0
Customer_Age              0
Gender                    0
Months_on_book            0
Dependent_count           0
Education_Level           0
Marital_Status            0
Card_Category             0
Credit_Limit              0
Months_Inactive_12_mon    0
Total_Trans_Amt           0
Attrition_Flag            0
dtype: int64

In [10]:
df.rename({"CLIENTNUM" : "id_cliente", "Customer_Age" : "idade", "Gender" : "sexo", "Months_on_book" : "tempo_cliente", "Dependent_count" : "dependentes", "Education_Level" : "nivel_educacao", "Marital_Status" : "estado_civil", "Card_Category" : "tipo_cartao", "Credit_Limit" : "limite_cartao", "Months_Inactive_12_mon" : "meses_inativo", "Total_Trans_Amt" : "total_transferido", "Attrition_Flag" : "cancelamento"}, axis=1, inplace=True)

/tmp/ipykernel_27195/1921650898.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename({"CLIENTNUM" : "id_cliente", "Customer_Age" : "idade", "Gender" : "sexo", "Months_on_book" : "tempo_cliente", "Dependent_count" : "dependentes", "Education_Level" : "nivel_educacao", "Marital_Status" : "estado_civil", "Card_Category" : "tipo_cartao", "Credit_Limit" : "limite_cartao", "Months_Inactive_12_mon" : "meses_inativo", "Total_Trans_Amt" : "total_transferido", "Attrition_Flag" : "cancelamento"}, axis=1, inplace=True)

In [18]:
set(df["nivel_educacao"])

{'Doutorado',
 'Ensino Fundamental',
 'Ensino Medio',
 'Faculdade',
 'Mestrado',
 'Pos-Graduacao'}

In [14]:
df = df.loc[df["nivel_educacao"] != "Unknown"]

In [17]:
df["nivel_educacao"].replace({"College" : "Faculdade", "Doctorate" : "Doutorado", "Graduate" : "Mestrado", "High School" : "Ensino Medio", "Post-Graduate" : "Pos-Graduacao", "Uneducated" : "Ensino Fundamental"}, inplace=True)

/tmp/ipykernel_27195/2171620079.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["nivel_educacao"].replace({"College" : "Faculdade", "Doctorate" : "Doutorado", "Graduate" : "Mestrado", "High School" : "Ensino Medio", "Post-Graduate" : "Pos-Graduacao", "Uneducated" : "Ensino Fundamental"}, inplace=True)
/tmp/ipykernel_27195/2171620079.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["nivel_educacao"].replace({"College" : "Faculdade", "Doctorate" : "Doutorado", "Graduate" : "Mestrado", "High School" : "Ensino Medio", "Post-Graduate" : "Pos-Graduacao", "Uneducated" : "Ensino Fundamental"}, inplace=True)

In [19]:
df

,id_cliente,idade,sexo,tempo_cliente,dependentes,nivel_educacao,estado_civil,tipo_cartao,limite_cartao,meses_inativo,total_transferido,cancelamento
0,768805383,45,M,39,3,Ensino Medio,Married,Blue,12691.0,1,1144,Existing Customer
1,818770008,49,F,44,5,Mestrado,Single,Blue,8256.0,1,1291,Existing Customer
2,713982108,51,M,36,3,Mestrado,Married,Blue,3418.0,1,1887,Existing Customer
3,769911858,40,F,34,4,Ensino Medio,Unknown,Blue,3313.0,4,1171,Existing Customer
4,709106358,40,M,21,3,Ensino Fundamental,Married,Blue,4716.0,1,816,Existing Customer
...,...,...,...,...,...,...,...,...,...,...,...,...
10121,713899383,56,F,50,1,Mestrado,Single,Blue,3688.0,1,14596,Existing Customer
10122,772366833,50,M,40,2,Mestrado,Single,Blue,4003.0,2,15476,Existing Customer
10124,716506083,44,F,36,1,Ensino Medio,Married,Blue,5409.0,3,10291,Attrited Customer
10125,717406983,30,M,36,2,Mestrado,Unknown,Blue,5281.0,3,8395,Attrited Customer
10126,714337233,43,F,25,2,Mestrado,Married,Silver,10388.0,2,10294,Attrited Customer

In [23]:
set(df["estado_civil"])

{'Casado', 'Divorciado', 'Solteiro'}

In [21]:
df = df.loc[df["estado_civil"] != 'Unknown']

In [22]:
df["estado_civil"].replace({"Divorced" : "Divorciado", "Married" : "Casado", "Single" : "Solteiro"}, inplace=True)

/tmp/ipykernel_27195/1701670775.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["estado_civil"].replace({"Divorced" : "Divorciado", "Married" : "Casado", "Single" : "Solteiro"}, inplace=True)
/tmp/ipykernel_27195/1701670775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["estado_civil"].replace({"Divorced" : "Divorciado", "Married" : "Casado", "Single" : "Solteiro"}, inplace=True)

In [27]:
set(df["cancelamento"])

{0, 1}

In [26]:
df["cancelamento"].replace({"Attrited Customer" : 1, "Existing Customer" : 0}, inplace=True)

/tmp/ipykernel_27195/1655779947.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["cancelamento"].replace({"Attrited Customer" : 1, "Existing Customer" : 0}, inplace=True)
/tmp/ipykernel_27195/1655779947.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["cancelamento"].replace({"Attrited Customer" : 1, "Existing Customer" : 0}, inplace=True)
/tmp/ipykernel_27195/1655779947.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["cancelamento"].replace({"Attrited Customer" : 1, "Existing Customer" : 0}, inplace=True)

In [29]:
df.to_csv("./Processadas/banco.csv", index=False)

In [30]:
df

,id_cliente,idade,sexo,tempo_cliente,dependentes,nivel_educacao,estado_civil,tipo_cartao,limite_cartao,meses_inativo,total_transferido,cancelamento
0,768805383,45,M,39,3,Ensino Medio,Casado,Blue,12691.0,1,1144,0
1,818770008,49,F,44,5,Mestrado,Solteiro,Blue,8256.0,1,1291,0
2,713982108,51,M,36,3,Mestrado,Casado,Blue,3418.0,1,1887,0
4,709106358,40,M,21,3,Ensino Fundamental,Casado,Blue,4716.0,1,816,0
5,713061558,44,M,36,2,Mestrado,Casado,Blue,4010.0,1,1088,0
...,...,...,...,...,...,...,...,...,...,...,...,...
10120,710841183,54,M,34,1,Ensino Medio,Solteiro,Blue,13940.0,2,15577,0
10121,713899383,56,F,50,1,Mestrado,Solteiro,Blue,3688.0,1,14596,0
10122,772366833,50,M,40,2,Mestrado,Solteiro,Blue,4003.0,2,15476,0
10124,716506083,44,F,36,1,Ensino Medio,Casado,Blue,5409.0,3,10291,1
10126,714337233,43,F,25,2,Mestrado,Casado,Silver,10388.0,2,10294,1

In [36]:
min(df["total_transferido"])

510

In [2]:
df = pd.read_csv("/home/ismael/Downloads/train.csv")

In [4]:
df.dropna(inplace=True)

In [7]:
df.columns

Index(['ID', 'Gender', 'Ever_Married', 'Age', 'Graduated', 'Profession',
       'Work_Experience', 'Spending_Score', 'Family_Size', 'Var_1',
       'Segmentation'],
      dtype='object')

In [44]:
df["Segmentation"].unique()

array(['D', 'B', 'C', 'A'], dtype=object)

In [26]:
df.replace({"Healthcare" : "Enfermeiro", "Engineer" : "Engenheiro", "Lawyer" : "Advogado", "Artist" : "Ator/Atriz", "Doctor" : "Medico", "Homemaker" : "Do Lar", "Entertainment" : "Entretenimento", "Executive" : "Executivo"}, inplace=True)

In [30]:
df["Spending_Score"].replace({"Low" : "Baixo", "High" : "Alto", "Average" : "Medio"}, inplace=True)

/tmp/ipykernel_897569/1806796904.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Spending_Score"].replace({"Low" : "Baixo", "High" : "Alto", "Average" : "Medio"}, inplace=True)

In [ ]:
df

In [45]:
df.to_csv("./Processadas/car_segmentation.csv", index=False)

In [49]:
!pip install readxl

ERROR: Could not find a version that satisfies the requirement readxl (from versions: none)
ERROR: No matching distribution found for readxl

[notice] A new release of pip is available: 23.0.1 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [47]:
import pyxl

ModuleNotFoundError: No module named 'pyxl'

In [54]:
df = pd.read_csv("/home/ismael/Downloads/marketing_campaign.xls", sep="\t")

In [55]:
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,Graduation,Married,61223.0,0,1,13-06-2013,46,709,...,5,0,0,0,0,0,0,3,11,0
2236,4001,1946,PhD,Together,64014.0,2,1,10-06-2014,56,406,...,7,0,0,0,1,0,0,3,11,0
2237,7270,1981,Graduation,Divorced,56981.0,0,0,25-01-2014,91,908,...,6,0,1,0,0,0,0,3,11,0
2238,8235,1956,Master,Together,69245.0,0,1,24-01-2014,8,428,...,3,0,0,0,0,0,0,3,11,0
2239,9405,1954,PhD,Married,52869.0,1,1,15-10-2012,40,84,...,7,0,0,0,0,0,0,3,11,1

In [56]:
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')

In [ ]:
df = df[["ID", "Year_Birth", "Education", "Marital_Status", "Income", "Kidhome", "Teenhome", "Recency", ""]]

In [58]:
df = pd.read_csv("./Processadas/car_segmentation.csv")

In [60]:
import numpy as np

In [61]:
df["ano_nascimento"] = np.random.randint(1954, 1998, len(df))

In [63]:
df["renda"] = 4000

In [64]:
set(df["Profession"])

{'Advogado',
 'Ator/Atriz',
 'Do Lar',
 'Enfermeiro',
 'Engenheiro',
 'Entretenimento',
 'Executivo',
 'Marketing',
 'Medico'}

In [93]:
p = "Medico"

In [94]:
df.loc[df["Profession"] == p, "renda"] = df.loc[df["Profession"] == p, "renda"]  + np.random.normal(3000, 2000, size=len(df.loc[df["Profession"] == p, "renda"]))

In [95]:
df.loc[df["Profession"] == p, "renda"]

10      11245.508930
26       7586.506965
30       9515.321823
54       7657.901976
63       6175.059103
            ...
6607    10220.855413
6614     9400.725781
6623     5079.543762
6629     7429.632777
6645     6647.713253
Name: renda, Length: 592, dtype: float64

In [99]:
df["tempo_ultima_compra"] = np.random.randint(0, 38, len(df))

In [101]:
df["automoveis_adquiridos"] = 1

In [108]:
df.loc[df["renda"] > 20000, "automoveis_adquiridos"] = np.random.choice([2,3,4,5], p=[0.1, 0.2, 0.4, 0.3], size=len(df.loc[df["renda"] > 20000, "automoveis_adquiridos"]))

In [118]:
df.loc[(df["renda"] > 5000) & (df["renda"] < 10000), "automoveis_adquiridos"] = np.random.choice([1, 2,3,4], p=[0.7, 0.28, 0.01, 0.01], size=len(df.loc[(df["renda"] > 5000) & (df["renda"] < 10000), "automoveis_adquiridos"]))

In [119]:
df.loc[(df["renda"] > 5000) & (df["renda"] < 10000), "automoveis_adquiridos"].value_counts()

automoveis_adquiridos
1    2062
2     790
4      34
3      17
Name: count, dtype: int64

In [130]:
df.loc[df["renda"] < 1000, "renda"] = 2000 + np.random.normal(400, 200, size=len(df.loc[df["renda"] < 1000]))

In [135]:
df.drop("ano_nascimento", inplace=True, axis=1)

In [137]:
df = df.loc[df["renda"] != 4000]

In [138]:
df["renda"] = np.round(df["renda"], 2)

/tmp/ipykernel_897569/939244227.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["renda"] = np.round(df["renda"], 2)

In [153]:
df["avalicao_cliente"] = np.random.choice([i for i in range(1, 11)], p=[0.01, 0.02, 0.03, 0.04, 0.07, 0.08, 0.1, 0.14, 0.2, 0.31], size=len(df))

/tmp/ipykernel_897569/3794676649.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["avalicao_cliente"] = np.random.choice([i for i in range(1, 11)], p=[0.01, 0.02, 0.03, 0.04, 0.07, 0.08, 0.1, 0.14, 0.2, 0.31], size=len(df))

In [154]:
df["avalicao_cliente"].value_counts()

avalicao_cliente
10    1811
9     1134
8      832
7      586
6      477
5      424
4      241
3      168
2      132
1       45
Name: count, dtype: int64

In [155]:
df.to_csv("./Processadas/car_segmentation_2.csv")

In [143]:
np.sum( )

np.float64(1.0)

In [150]:
[i for i in range(1, 11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]